"""Simulation constants ported from the JavaScript project."""

CHASSIS_LENGTH = 4.0
CHASSIS_WIDTH = 1.5
CHASSIS_WHEEL_WIDTH = 1.2
CHASSIS_FRONT_WHEEL_SHIFT = 1.3
CHASSIS_BACK_WHEEL_SHIFT = -1.15

PARKING_SPOT_POSITION = (-3.6, -2.1)
PARKING_INNER_WIDTH = CHASSIS_WIDTH
PARKING_INNER_LENGTH = CHASSIS_LENGTH
